adapters:
- config:
    check_napcat_update: false
    enable_webui: false
    remote_mode: true
    report_forward_message_detail: true
    report_self_message: false
    stop_napcat: false
    webui_token: NcatBot
    webui_uri: http://localhost:6099
    ws_listen_ip: localhost
    ws_token: he031701
    ws_uri: ws://101.35.164.122:3001
  enabled: true
  platform: qq
  type: napcat
bot_uin: '58805194'
bt_uin: '58805194'
check_ncatbot_update: true
debug: false
enable_webui_interaction: false
logging:
  event_log_levels:
    meta_event: NONE
plugin:
  auto_install_pip_deps: true
  load_plugin: false
  plugin_blacklist: []
  plugin_configs: {}
  plugin_whitelist: []
  plugins_dir: plugins
  skip_plugin_load: false
root: '123456'
skip_ncatbot_install_check: false
websocket_timeout: 15
